"""Add email column

Revision ID: 4cd3cba23dfb
Revises: fd22a78267b6
Create Date: 2023-11-01 20:21:31.893572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd3cba23dfb'
down_revision: Union[str, None] = 'fd22a78267b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_players_email'), 'players', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_email'), table_name='players')
    op.drop_column('players', 'email')
    # ### end Alembic commands ###
