version: '3.9'

services:
  auth_db:
    image: postgres:16-alpine
    container_name: auth_postgres
    ports:
      - 5432:5432
    volumes:
      - ~/data/auth_postgres:/var/lib/postgresql/data
    env_file:
      .env
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "auth_db", "-U", "auth_user"]
      interval: 5s
      timeout: 5s
      retries: 5
  auth_api:
    build: ./auth
    container_name: auth_api
    command: bash -c "alembic upgrade head && uvicorn auth.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=auth_db
      - AUTH_DB_HOST=auth_db
    env_file:
      .env
    depends_on:
      auth_db:
        condition: service_healthy
  # db:
  #   image: postgres:16-alpine
  #   container_name: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/data/postgres:/var/lib/postgresql/data
  #   env_file:
  #     .env
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-d", "pool_db", "-U", "pool_user"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  # api:
  #   build: ./api
  #   container_name: api
  #   command: bash -c "alembic upgrade head && uvicorn db.main:app --host 0.0.0.0 --port 8000"
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - POSTGRES_HOST=db
  #   env_file:
  #     .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  # ui:
    # build: ./ui
    # container_name: ui
    # environment:
      # VITE_API_URL: http://api:8000/
    # ports:
      # - 80:80
    # depends_on:
      # - api
