version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    env_file:
      .env
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "pool_db", "-U", "pool_user"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: ./api
    container_name: api
    command: bash -c "alembic upgrade head && uvicorn db.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=db
    env_file:
      .env
    depends_on:
      db:
        condition: service_healthy
  ui:
    build: ./ui
    container_name: ui
    ports:
      - 80:80
    depends_on:
      - api