version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    env_file:
      .env
  api:
    build: ./api
    container_name: api
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=db
    env_file:
      .env
    depends_on:
      - db